### ISSUE TITLE
pyaudio error

### ISSUE THREAD

**Issue by vitiennam** [piraka9011/dialogflow_ros#14]
Hi,

I got this error when I run `roslaunch dialogflow_ros dialogflow.launch`:
![image](https://user-images.githubusercontent.com/20283416/66380770-41f58180-e9e2-11e9-9a2c-5a26058b83fb.png)

Thanks

**Comment by piraka9011** [comment]
That isn't an error, just a warning from ALSA. Dialogflow should still be working. (you can see DF_CLIENT says its ready and spinning).

You can reconfigure ALSA however I don't recommend playing around with those settings unless you know what you're doing.
